export const SET_TOKEN = 'SET_TOKEN';

export const SET_HOME_PAGE_PRODUCTS = 'SET_HOME_PAGE_PRODUCTS';

export const SET_USER = 'SET_USER';

export const SET_CATEGORY_PAGE_PRODUCTS = 'SET_CATEGORY_PAGE_PRODUCTS';

export const UPDATE_PRODUCT_QUANTITY = 'UPDATE_PRODUCT_QUANTITY';

export const SET_PRODUCT_QUANTITY = 'SET_PRODUCT_QUANTITY';
